##### Lab 13 Image Classification Using Pre-trained CNN Models

###### Part I
##### importing the VGG16 and Create Model

In [1]:
import os
import glob
import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras.applications.vgg16 import VGG16
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from keras.utils import load_img
import matplotlib.pyplot as plt
from keras.preprocessing.image import *

In [2]:
model = VGG16(weights = 'imagenet')

In [3]:
model.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

##### Loading the own image of ourselves

In [ ]:
#Load flower jpeg image from local and set target size to 224 x 224
img = tf.keras.utils.load_img('dataset/my/my1.jpg', target_size=(224,224))

In [5]:
img =  tf.keras.utils.img_to_array(img)
img = np.expand_dims(img, axis = 0)
img

array([[[[199., 206., 212.],
         [194., 206., 218.],
         [198., 204., 218.],
         ...,
         [ 62.,  50.,  64.],
         [ 59.,  48.,  65.],
         [ 65.,  47.,  71.]],

        [[198., 205., 211.],
         [194., 207., 216.],
         [199., 205., 219.],
         ...,
         [ 67.,  51.,  64.],
         [ 63.,  50.,  67.],
         [ 64.,  49.,  70.]],

        [[197., 206., 213.],
         [197., 207., 216.],
         [199., 207., 220.],
         ...,
         [ 62.,  50.,  62.],
         [ 54.,  48.,  60.],
         [ 54.,  50.,  65.]],

        ...,

        [[150., 159., 166.],
         [150., 158., 161.],
         [151., 163., 163.],
         ...,
         [103.,  94.,  99.],
         [ 91.,  86.,  90.],
         [ 75.,  68.,  75.]],

        [[150., 154., 165.],
         [153., 158., 164.],
         [151., 163., 163.],
         ...,
         [103.,  99.,  98.],
         [ 97.,  97.,  95.],
         [ 91.,  89.,  90.]],

        [[152., 151., 165.],
       

##### print prediction

In [6]:
predicted = model.predict(img)

1/1 [==============================] - 1s 815ms/step


In [7]:
predicted

array([[1.43741952e-08, 1.70574222e-05, 2.69754310e-06, 3.57139152e-06,
        5.48633443e-06, 7.44542149e-06, 2.70002565e-05, 4.00342105e-06,
        1.95902840e-06, 1.31970026e-07, 6.53769291e-07, 2.54882508e-07,
        3.68557858e-06, 2.79291976e-06, 8.15005137e-07, 5.37748747e-07,
        2.26717634e-06, 1.69611894e-06, 3.60916260e-07, 8.04823958e-06,
        8.83300899e-08, 4.15347102e-07, 7.30419572e-07, 2.84045382e-06,
        1.45409717e-06, 7.78138514e-08, 1.00955909e-07, 7.92605192e-07,
        2.48146137e-07, 2.53836276e-07, 3.93603479e-08, 2.38456118e-06,
        2.78112765e-07, 3.13518029e-07, 4.59249520e-07, 6.60938113e-08,
        8.05570721e-07, 1.34660965e-07, 8.71297232e-07, 9.86903274e-07,
        3.00941588e-06, 1.82067996e-08, 4.86629290e-07, 3.47732362e-06,
        6.04793158e-08, 1.62097501e-06, 2.40236295e-06, 5.56129294e-07,
        1.59851965e-07, 9.23169097e-08, 1.95552360e-07, 1.17843174e-05,
        7.26404380e-07, 3.43703590e-07, 2.81998496e-07, 4.058504

In [8]:

top_five_predict = tf.keras.applications.vgg16.decode_predictions(predicted,
                                                                  top=5)
top_five_predict

[[('n03930313', 'picket_fence', 0.30994618),
  ('n04209239', 'shower_curtain', 0.10546545),
  ('n03125729', 'cradle', 0.051257648),
  ('n03630383', 'lab_coat', 0.04397586),
  ('n04040759', 'radiator', 0.038844887)]]

##### Part II <br> ResNet


In [9]:
from tensorflow.keras.applications.resnet50 import ResNet50
model_rn = ResNet50()

In [10]:
model_rn.summary()

Model: "resnet50"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 230, 230, 3)  0           ['input_2[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 112, 112, 64  9472        ['conv1_pad[0][0]']              
                                )                                                                 
                                                                                           

##### Fitting the already Preprocessed Image

In [11]:
pred_rn = model_rn.predict(img)
pred_rn

1/1 [==============================] - 3s 3s/step


array([[6.44073950e-08, 8.00167327e-05, 1.22529843e-06, 1.23964128e-06,
        2.14059924e-06, 1.61341757e-06, 8.18654598e-07, 1.75997445e-06,
        4.94668825e-07, 2.26272533e-07, 7.49376028e-08, 1.12192218e-07,
        1.72050363e-06, 6.56279781e-07, 1.06240952e-06, 2.70898795e-07,
        4.18917324e-07, 3.00977990e-06, 2.34094387e-07, 2.53096709e-06,
        4.26036095e-09, 4.41660255e-08, 2.14664936e-07, 1.10548839e-07,
        1.06372147e-06, 7.41301989e-08, 8.48190762e-09, 1.09723061e-07,
        1.28603489e-07, 1.01443469e-07, 3.10018521e-07, 7.24031395e-07,
        7.65251542e-08, 7.28557097e-07, 1.82833489e-07, 2.73232779e-08,
        9.42311488e-07, 8.62004754e-07, 6.22608098e-08, 9.04033470e-07,
        1.15222440e-06, 4.12711998e-08, 3.85271989e-07, 9.21240769e-07,
        1.48251843e-07, 5.07724110e-07, 1.17017180e-06, 1.81517265e-07,
        1.46475770e-07, 5.22462713e-08, 2.50810467e-06, 6.04388079e-05,
        7.02443629e-07, 7.39549080e-07, 9.33601711e-07, 5.416372

In [12]:

top_five_predict = tf.keras.applications.resnet50.decode_predictions(predicted,
                                                                  top=5)
top_five_predict 

[[('n03930313', 'picket_fence', 0.30994618),
  ('n04209239', 'shower_curtain', 0.10546545),
  ('n03125729', 'cradle', 0.051257648),
  ('n03630383', 'lab_coat', 0.04397586),
  ('n04040759', 'radiator', 0.038844887)]]

##### part III

In [13]:


for i in glob.glob("dataset/my/WIN_20220915_20_15_34_Pro.jpg"):
    img = tf.keras.utils.load_img(i, target_size=(224,224))
    img =  tf.keras.utils.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    img

In [14]:
len(img)

1

In [15]:
p2=model.predict(img)
p2

1/1 [==============================] - 0s 378ms/step


array([[3.37356667e-08, 3.86054262e-06, 5.53904010e-06, 1.31988063e-05,
        2.79522683e-05, 1.85639292e-05, 6.29416609e-05, 2.57056263e-06,
        3.70775609e-07, 9.76695418e-08, 2.36526802e-07, 2.80604638e-07,
        1.67524013e-06, 1.34106790e-06, 6.06012918e-07, 1.75665903e-07,
        8.64689184e-07, 1.77125833e-06, 1.29602796e-07, 2.97685597e-06,
        3.81046377e-08, 4.50374642e-07, 4.64282152e-07, 5.16730779e-06,
        1.00058435e-06, 7.60825216e-08, 7.01973377e-08, 5.38034612e-07,
        2.85179027e-07, 8.69014087e-08, 2.35834108e-08, 1.20642892e-06,
        1.84631489e-07, 3.89770122e-07, 4.44977388e-07, 2.40178171e-08,
        2.12317090e-07, 4.50162290e-08, 1.84220721e-06, 1.67146925e-06,
        2.43037584e-06, 2.71036473e-08, 6.98614429e-07, 7.63195112e-06,
        7.05259353e-08, 2.09017776e-06, 2.29441594e-06, 1.25821725e-06,
        1.50804112e-07, 7.13133304e-08, 1.88798040e-07, 1.88829908e-05,
        1.17764500e-06, 5.41489669e-07, 6.55460610e-07, 1.508803

In [16]:

top_ten_predict = tf.keras.applications.vgg16.decode_predictions(p2,
                                                                  top=10)
top_ten_predict

[[('n04209239', 'shower_curtain', 0.13559519),
  ('n03930313', 'picket_fence', 0.13309282),
  ('n04532106', 'vestment', 0.07488363),
  ('n02883205', 'bow_tie', 0.07268062),
  ('n02667093', 'abaya', 0.063785955),
  ('n03041632', 'cleaver', 0.045067225),
  ('n03424325', 'gasmask', 0.033823427),
  ('n03630383', 'lab_coat', 0.0309208),
  ('n04429376', 'throne', 0.030171642),
  ('n04208210', 'shovel', 0.019109752)]]

In [17]:
#resnet 
r2 =model_rn.predict(img)
r2

1/1 [==============================] - 0s 233ms/step


array([[4.38361752e-07, 2.56835210e-05, 1.26975801e-05, 1.63512038e-06,
        1.07402948e-05, 1.65135714e-06, 1.55381167e-06, 7.48152331e-07,
        4.23510670e-07, 5.53412036e-08, 3.21542686e-08, 2.80157781e-08,
        6.11641099e-07, 1.47501410e-07, 1.62955519e-06, 8.88717651e-08,
        9.62360787e-08, 2.10573216e-06, 1.15759278e-07, 1.35844311e-06,
        2.43630005e-09, 5.86400972e-07, 1.97103518e-07, 9.22492021e-08,
        7.57501721e-06, 7.11039831e-08, 6.41383879e-09, 3.70101333e-07,
        1.44533345e-07, 5.68534091e-08, 6.09404140e-07, 2.00753675e-07,
        6.22578753e-08, 4.21160905e-07, 2.75321213e-07, 2.16379359e-08,
        2.15745740e-06, 1.32229320e-06, 3.31022640e-08, 7.15321050e-07,
        3.91052936e-07, 8.47131076e-08, 6.06296453e-07, 1.77133325e-06,
        3.75192457e-07, 2.57359659e-07, 1.34629920e-06, 2.40346765e-07,
        6.96281646e-08, 1.40601593e-08, 7.66212054e-07, 7.31443015e-06,
        1.47047695e-06, 5.44475415e-06, 3.07112100e-06, 6.132163

In [18]:

top_ten_predict = tf.keras.applications.resnet50.decode_predictions(r2,
                                                                  top=10)
top_ten_predict

[[('n04584207', 'wig', 0.28771207),
  ('n03970156', 'plunger', 0.07069304),
  ('n03724870', 'mask', 0.066072814),
  ('n03476991', 'hair_spray', 0.053358447),
  ('n07615774', 'ice_lolly', 0.043197062),
  ('n04458633', 'totem_pole', 0.042107802),
  ('n04357314', 'sunscreen', 0.040385533),
  ('n04525305', 'vending_machine', 0.025298761),
  ('n04154565', 'screwdriver', 0.022876482),
  ('n04579432', 'whistle', 0.020137265)]]

##### Part IV

##### Rotation

In [19]:
datagen = ImageDataGenerator(
        rotation_range=10, # rotation
        width_shift_range=0.2, # horizontal shift
        height_shift_range=0.2, # vertical shift
        zoom_range=0.2, # zoom
        horizontal_flip=True, # horizontal flip
        brightness_range=[0.2,1.2]) # brightness

In [20]:
trdata = ImageDataGenerator(rotation_range=90, 
                                     brightness_range=[0.1, 0.7],
                                     width_shift_range=0.5, 
                                     height_shift_range=0.5,
                                     horizontal_flip=True, 
                                     vertical_flip=True,
                                     validation_split=0.15)
traindata = trdata.flow_from_directory(directory=r"dataset/food",target_size=(224,224))

tsdata = ImageDataGenerator(rotation_range=90, 
                                     brightness_range=[0.1, 0.7],
                                     width_shift_range=0.5, 
                                     height_shift_range=0.5,
                                     horizontal_flip=True, 
                                     vertical_flip=True,
                                     validation_split=0.15)
testdata = tsdata.flow_from_directory(directory=r"dataset/food", target_size=(224,224))

Found 26 images belonging to 3 classes.
Found 26 images belonging to 3 classes.


In [23]:
model_rn.fit_generator(datagen.flow(traindata,testdata,
                                batch_size=32),
                   steps_per_epoch = x_train.shape[0]//batch_size,
                   epochs = 15,
                   validation_data = (x_test,y_test))

KeyboardInterrupt: 